version: '3.8'
services:
  rode-battle-worker:
    container_name: rode-battle-worker-management
    image: ${DOCKER_HUB_URL}/rode-be-worker:nightly
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}


