name: CD R.ODE Backend Worker Rust
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  socket-worker-build:
    name: Build source code to Docker image
    runs-on: fcode-japao-runner
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
          
      - name: DockerHub Login
        run: echo ${{ secrets.F_CODE_DOCKER_PASS }} | docker login -u ${{ secrets.F_CODE_DOCKER_USER }} --password-stdin ${{secrets.F_CODE_DOCKER_REGISTRY_URL}}
      - name: Build Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            DB_URL=postgres://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@${{secrets.DB_HOST_LAN}}/${{secrets.DB_DATABASE}}
          tags: ${{ secrets.F_CODE_DOCKER_REGISTRY_URL }}/rode-be-worker:${{ github.ref_name == 'main' && 'stable' || 'nightly' }}
  
  staging-worker-deploy:
    name: Deploy Socket Worker to F-Code Server
    runs-on: fcode-japao-runner
    needs: socket-worker-build
    env:
      DATABASE_URL: postgres://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@${{secrets.DB_HOST}}/${{secrets.DB_DATABASE}}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3
    - name: DockerHub Login
      run: echo ${{ secrets.F_CODE_DOCKER_PASS }} | docker login -u ${{ secrets.F_CODE_DOCKER_USER }} --password-stdin ${{secrets.F_CODE_DOCKER_REGISTRY_URL}}
    - name: Clean Container, Image And Prepare For Deploy
      run: docker compose -f docker-compose.test.yaml -p rode-be-worker down --rmi all -v
    - name: Deploy Socket Worker
      run: docker compose -f docker-compose.test.yaml -p rode-be-worker up -d